### ISSUE TITLE
Try to locate missing `sl-0.1.jar`

### ISSUE THREAD

**Issue by duncdrum** [hcts-hra/lucene-transcoding-analyzer#10]

**Comment by pao-pirka** [comment]
**Gesucht via:**
find / -iname lucene-transcoding-*
find / -iname sl-0.1.jar
find / -iname lucene-*.jar
find / -iname *sanskritlibrary*
Auch in den jeweiligen /home suchen lassen.

**Durchgeführt auf folgenden Servern:** 
1. sv002
2. sv013
3. sv035: bei der Gelegenheit updates+upgrades machen lassen
4. sv036: bei der Gelegenheit updates+upgrades machen lassen
5. sv037: bei der Gelegenheit updates+upgrades machen lassen
